version: '1'
x-volume-mounts: &volume_definition
    - ~/.aws:/home/glue_user/.aws
    - ~/<your path to glue jobs>/glue_jobs:/home/glue_user/workspace/jupyter_workspace/
services:
  glue_jupyter:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: glue_jupyter_lab
    volumes: *volume_definition
    environment:
      - AWS_PROFILE=default
      - DISABLE_SSL=true
      - PYTHONPATH=/home/glue_user/workspace/jupyter_workspace/lib
    ports:
      - "4040:4040"
      - "18080:18080"
      - "8998:8998"
      - "8888:8888"
    command: /home/glue_user/jupyter/jupyter_start.sh
  
  glue_script:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: glue_spark_submit
    command: spark-submit /home/glue_user/workspace/jupyter_workspace/the_glue_job_one/src/job_one.py
    environment:
      - AWS_PROFILE=default
      - DISABLE_SSL=true
      - PYTHONPATH=/home/glue_user/workspace/jupyter_workspace/lib
    volumes: *volume_definition
    ports:
      - "4040:4040"
      - "18080:18080"
    stdin_open: true
    tty: true
    restart: "no"
